---
- name: Playbook for serial and max fail prcentage implementation
  hosts: all
  max_fail_percentage: 10
#  serial: 1
#  serial:   # stepup configuration, first on 1 node, next execution on 3 notes, next execution on 5
#  - 1
#  - 3
#  - 5
  serial:
  - "10%"
  - "90%"
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: Installing elinks serially one node at a time
    yum:
     name: elinks
     state: latest
  - name: Installing git  # Intentional checking for git intallation failure because of apt module in centos (To verify max failure percentage)
    apt:
     name: git
     state: present
