---
- name: "Playbook for run_once implementation"
  hosts: centos
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: Installing elinks serially one node at a time
    yum:
     name: elinks
     state: latest
    delegate_to: localhost
    run_once: yes
