---
- name: jinja templates sample playbook
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    name_var: vinay kumar
    age_var: 28
  tasks:
  - name: copying template file to some location
    template:
     src: sampleConf.j2
     dest: /home/ansible/createdconf.config
     owner: ansible
     group: ansible
     mode: 0777
     validate: cat %s
